local vsc = require("vscode")
local map = vim.keymap.set
-- Exit insert mode
vim.keymap.set("i", "jk", "<Esc>", { desc = "Exit insert mode" })
vim.keymap.set("i", "kj", "<Esc>", { desc = "Exit insert mode" })

-- Window navigation (override your C-h/j/k/l to use VSCode pane navigation)
map("n", "<C-h>", function()
	vsc.action("workbench.action.navigateLeft")
end)
map("n", "<C-l>", function()
	vsc.action("workbench.action.navigateRight")
end)
map("n", "<C-k>", function()
	vsc.action("workbench.action.navigateUp")
end)
map("n", "<C-j>", function()
	vsc.action("workbench.action.navigateDown")
end)

-- File finding (replaces telescope)
map("n", "<leader>ff", function()
	vsc.action("workbench.action.quickOpen")
end)
map("n", "<leader>fg", function()
	vsc.action("workbench.action.findInFiles")
end)
map("n", "<leader>fb", function()
	vsc.action("workbench.action.showAllEditors")
end)

-- File explorer (replaces nvim-tree)
map("n", "<leader>e", function()
	vsc.action("workbench.action.toggleSidebarVisibility")
end)

-- LSP
map("n", "gd", function()
	vsc.action("editor.action.revealDefinition")
end)
map("n", "gr", function()
	vsc.action("editor.action.goToReferences")
end)
map("n", "K", function()
	vsc.action("editor.action.showHover")
end)
map("n", "<leader>rn", function()
	vsc.action("editor.action.rename")
end)
map("n", "<leader>ca", function()
	vsc.action("editor.action.quickFix")
end)
map("n", "[d", function()
	vsc.action("editor.action.marker.prev")
end)
map("n", "]d", function()
	vsc.action("editor.action.marker.next")
end)

-- Git (replaces fugitive/gitsigns)
map("n", "<leader>gs", function()
	vsc.action("workbench.view.scm")
end)
map("n", "]g", function()
	vsc.action("workbench.action.editor.nextChange")
end)
map("n", "[g", function()
	vsc.action("workbench.action.editor.previousChange")
end)

-- Harpoon → editor tabs
map("n", "<leader>ha", function()
	vsc.action("workbench.action.pinEditor")
end)
map("n", "<leader>hh", function()
	vsc.action("workbench.action.showAllEditors")
end)

-- Comments
map({ "n", "v" }, "gcc", function()
	vsc.action("editor.action.commentLine")
end)
